# .pages.yml
title: My Blog Site
media:
  input: "assets/images"
  output: "/assets/images"

content:
  - name: posts
    label: Blog Posts
    type: collection
    path: "_posts"
    extension: "md"
    format: "yaml-frontmatter"
    filename: "{year}-{month}-{day}-{slug}"
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: body
        label: Content
        type: rich-text