# .pages.yml
title: My Blog Site
media:
  input: "assets/images"
  output: "/assets/images"

content:
  - slug:posts              # This defines your "collection"
    label: Blog Posts
    type: collection
    path: "_posts"          # This tells CMS to look in the _posts folder
    format: "yaml-frontmatter"
    filename: "{year}-{month}-{day}-{slug}"
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: body
        label: Content
        type: rich-text
